### PR TITLE
Enable or disable NSMenuItems correctly

### PR DESCRIPTION
**Pull request by williameveretteggplant**
Set the flags for NSMenuItems based on whether or not the items are enabled.

### CODE REVIEW

**Comment by qmfrederik** [comment]
LGTM.  Forcing the `MF_ENABLED` flag seems wrong.  This was done in 65ac16e16192d3745bd73f7b11c1de9c08364406, as a "temporary fix" four years ago.

@rfm @fredkiefer @gcasa - any thoughts?  If not, I'll merge this early next week.

**Comment by gcasa** [comment]
I have no problem as long as the proposed solution works better.  Also, as the saying goes, there is nothing so permanent as a "temporary fix." :)

**Comment by fredkiefer** [comment]
This just reverts the change Gregory made four years ago. Does anybody remember what the issue at that time was? Is there anything on the mailing lists?

**Comment by qmfrederik** [comment]
@fredkiefer The underlying issue is described in https://github.com/gnustep/libs-gui/pull/304: the enabled/disabled state of the menus doesn't get updated correctly on Windows (at least when using WinUXTheme).  65ac16e16192d3745bd73f7b11c1de9c08364406 forcefully enabled all menus.  https://github.com/gnustep/libs-gui/pull/304 (in tis current state) together this this PR causes the menus to behave as they should.

If you agree, I'd suggest we merge this PR (as the current implementation _always_ enables menus on Windows, which is wrong) and continue the work on https://github.com/gnustep/libs-gui/pull/304 to make sure the enabled/disabled state of those menus is correctly set.

**Comment by fredkiefer** [comment]
Thank you for explaining this. So with the other MR hopefully following in a few weeks, I think we should merge this.

**Review by fredkiefer — APPROVED** [review]
Looks like a good way to progress to a real solution.

**Pull request merged**
